### ISSUE TITLE
feature request for AppStoreServerAPIClient - http client abstraction

### ISSUE THREAD

**Issue by robtha** [apple/app-store-server-library-java#102]
it would be great if AppStoreServerAPIClient provides the ability to use different http client libraries (e.g. apache http components or jdk HttpClient).

**Comment by alexanderjordanbaker** [comment]
@robtha Would you be looking for a protected method on AppStoreServerAPIClient that takes in and returns Map, String, etc. that can be overridden as desired by users of the library so that isn't tied to okhttp?

**Comment by robtha** [comment]
@alexanderjordanbaker Yes, that would be sufficient in my opinion. maybe provided by an abstract base class. an implementation using OkHttp can then be provided by a specific subclass. 
A complete abstraction of http client (as implemented in springframework, for example) is actually not necessary.

kind regards

**Comment by alexanderjordanbaker** [comment]
@robtha Please check out https://github.com/apple/app-store-server-library-java/pull/109 and let me know if this would be what you are looking for

**Comment by robtha** [comment]
@alexanderjordanbaker many thanks for your quick response, I will try to check it out this week

**Comment by robtha** [comment]
@alexanderjordanbaker - today I checked out #109 and implemented an api client based on apache http components client 5.3.1 (see attached source). works great for me.
[HcAppStoreServerAPIClient.zip](https://github.com/user-attachments/files/16082702/HcAppStoreServerAPIClient.zip)

**Comment by alexanderjordanbaker** [comment]
Great, will get this out in a 3.0 soonish

**Comment by alexanderjordanbaker** [comment]
Version 3.0.0 was just released
