### ISSUE TITLE
v2.2.0 is not available on Maven Central

### ISSUE THREAD

**Issue by ndson040496** [apple/app-store-server-library-java#107]
https://mvnrepository.com/artifact/com.apple.itunes.storekit/app-store-server-library

The latest version is 2.1.0

**Comment by alexanderjordanbaker** [comment]
@ndson040496 Sorry I didn't notice the job for publishing failed, it should be available in a few minutes on Maven Central

**Comment by ndson040496** [comment]
Thank you, v2.2.0 is working now.

**Comment by ndson040496** [comment]
A little odd though, the mvn website still doesn't show 2.2.0, but I can import this version
