### ISSUE TITLE
Allow JWS online checks to be modified at runtime

### ISSUE THREAD

**Issue by damonho** [apple/app-store-server-library-java#118]
Hi, we are looking into having more control over when online checks are used in the `SignedDataVerifier`. Currently theres no way for us to enable/disable it at runtime and if we wanted to be able to do so we would need to create 2 instances of it with different `enableOnlineChecks` values at creation.

Wondering if we can add a setter for the enableOnlineChecks field in the `SignedDataVerifier`?

**Comment by alexanderjordanbaker** [comment]
SignedDataVerifier is designed to be created a locked with a specific function, in this case I would recommend making two signed data verifiers if needed
