### ISSUE TITLE
Problems using library 

### ISSUE THREAD

**Issue by entlog** [apple/app-store-server-library-java#121]
Hi,

   I am not sure if this is a problem in the project so I apologize for the inconvenience. I tried to create the code to see information about an in app purchase but when I execute it I am receiving the error NoSuchFieldError: JAVA_NET_AUTHENTICATOR. More specifically:
`Caused by: java.lang.NoSuchFieldError: JAVA_NET_AUTHENTICATOR
        at com.apple.itunes.storekit.client.AppStoreServerAPIClient.<init>(AppStoreServerAPIClient.java:50)
        at com.apple.itunes.storekit.client.AppStoreServerAPIClient.<init>(AppStoreServerAPIClient.java:38)
        at es.namepending.gamegym.service.InAppPurchaseService.validateIOSPurchase(InAppPurchaseService.java:88)`

I am not sure what I did wrong. I am using jdk 1.18 and embedded the code in a springboot project. This is the code:

```
public boolean validateIOSPurchase(String sReceipt) throws GymException {
      try {
         ObjectMapper mapper = new ObjectMapper();
         IOSReceipt receipt = mapper.readValue(sReceipt, IOSReceipt.class);
         String issuerId = "xxxxxx-xxxx-xxx-xxxx-xxxxxxxxxxxx";
         String keyId = "XXXXXX";
         String bundleId = "xxxx.yyy.zzzz";
         String encodedKey = null;
         
         // TODO: REVIEW Other values
         Environment environment = Environment.SANDBOX;
         
         try (InputStream is = InAppPurchaseEndpoint.class.getResourceAsStream(IOS_PRIVATEKEY_PATH)) {
            
            encodedKey = new BufferedReader(new InputStreamReader(is)).lines().collect(Collectors.joining("\n"));
         } catch (Exception e) {
            log.error("Problems reading ios private key: ", e);
            throw new GymException(GymException.CODE_UNEXPECTED, "Problems reading ios private key");
         }
         log.info("Obtained encoded key: " + encodedKey);
         AppStoreServerAPIClient client =
         new AppStoreServerAPIClient(encodedKey, keyId, issuerId, bundleId, environment);
         
         ReceiptUtility receiptUtil = new ReceiptUtility();
         String transactionId = receiptUtil.extractTransactionIdFromAppReceipt(receipt.transactionReceipt);
         if (transactionId != null) {
            TransactionHistoryRequest request = new TransactionHistoryRequest()
            .sort(TransactionHistoryRequest.Order.ASCENDING)
            .revoked(false)
            .productTypes(List.of(TransactionHistoryRequest.ProductType.AUTO_RENEWABLE));
            HistoryResponse response = null;
            List<String> transactions = new LinkedList<>();
            do {
               String revision = response != null ? response.getRevision() : null;
               response = client.getTransactionHistory(transactionId, revision, request, GetTransactionHistoryVersion.V2);
               transactions.addAll(response.getSignedTransactions());
            } while (response.getHasMore());
            log.info("[IAPS] Obtained list of transactions" + transactions);
         }
         return true;
      } catch (Exception ioe) {
         log.error("Exception validating IOS subscription", ioe);
         throw new GymException(GymException.CODE_UNEXPECTED, "Problems validating subscription");
      }
   }
```

I googled the problem with the JAVA_NET_AUTHENTICATOR but the only thing I see is related to versions of libraries in compilation. I used jdk 1.18 for building and executing (./gradlew bootRun). I cleaned the project but same result.

**Comment by alexanderjordanbaker** [comment]
@entlog This would be caused if the version of okhttp you have is different from the library. What version of okhttp are you using?

**Comment by entlog** [comment]
Thanks a lot for the response. I think you are right. I don't declare the okhttp dependency but I saw that it is decided as follows:

```
./gradlew -q backend:dependencyInsight --dependency com.squareup.okhttp3:okhttp --configuration runtimeClasspath 
Environment: [server.ssl.key-store-password:, api.auth.mockId:-1, resources.BACKGROUND.dir:/Users/entlog/Projects/Gymonauts/runtimeresources/restmp, jdbc.url:jdbc:mysql://127.0.0.1:3306/Gymonauts?autoreconnect=true, spring.datasource.password:somePassword, logs.folder:/Users/entlog/Projects/Gymonauts/logs, spring.datasource.username:gym, server.port:8080, api.auth.mockType:None, server.ssl.key-store:, resources.LOGO.dir:/Users/entlog/Projects/Gymonauts/runtimeresources/restmp, server.baseurl:http://192.168.68.9:8080, server.ssl.enabled:false]
com.squareup.okhttp3:okhttp:3.14.9
   variant "runtime" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-runtime
      org.gradle.libraryelements     = jar
      org.gradle.category            = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.environment     = standard-jvm
         org.gradle.jvm.version         = 11
   ]
   Selection reasons:
      - Selected by rule
      - By constraint : app-store-server-lib uses it

com.squareup.okhttp3:okhttp:4.12.0 -> 3.14.9
+--- runtimeClasspath
\--- com.apple.itunes.storekit:app-store-server-library:3.1.0
     \--- runtimeClasspath
```

I don't know how to force the 4.12.0 version. I have no other dependency that I can see in the gradle files :-/ nor it is shown in the insight.

**Comment by entlog** [comment]
Ok, I kept investigating and it seems that it is related to the springboot dependencies. I forced the version in the gradle.properties with:

`okhttp3.version=4.12.0`

But now I have another error that probably is the same with another library...

```
Caused by: java.lang.NoSuchMethodError: 'boolean org.bouncycastle.asn1.ASN1Integer.hasValue(int)'
        at com.apple.itunes.storekit.migration.ReceiptUtility.lambda$extractTransactionIdFromAppReceipt$2(ReceiptUtility.java:57)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
```

In any case, many thanks @alexanderjordanbaker for your time.

**Comment by alexanderjordanbaker** [comment]
@entlog This appears to be a similar issue with bouncycastle's version.

The library has a very small number of direct runtime dependencies (4) https://github.com/apple/app-store-server-library-java/blob/ef407303327ded1849396d684ef63561c177d186/build.gradle#L9

I would recommend looking at these and making sure they do not conflict with any versions your project is bringing in.

**Comment by entlog** [comment]
Thanks @alexanderjordanbaker for the response. In the end I had to implement it manually. It was all due to the spring boot version in the project and upgrading it would take a loot of time so I had to implement the jwt logic myself. 
In any case I am really grateful for your help.

Best regards.
