### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchFieldError: JAVA_NET_AUTHENTICATOR

### ISSUE THREAD

**Issue by wutianaaa** [apple/app-store-server-library-java#124]
![1727431158821](https://github.com/user-attachments/assets/4f621dd0-2293-4891-9814-6de9abddfdd5)
这个报错是因为什么，授权一直失败

**Comment by alexanderjordanbaker** [comment]
@wutianaaa Please make sure the version of okhttp matches the version the library expects

**Comment by alexanderjordanbaker** [comment]
Closing due to staleness, please reopen if needed
