### ISSUE TITLE
Handler dispatch failed: java.lang.NoSuchMethodError: 'boolean org.bouncycastle.asn1.ASN1Integer.hasValue(int)'

### ISSUE THREAD

**Issue by linkaiqq** [apple/app-store-server-library-java#129]
AppStoreServerAPIClient client = new AppStoreServerAPIClient(encodedKey, keyId, issuerId, bundleId, Environment.PRODUCTION);
ReceiptUtility receiptUtil = new ReceiptUtility();
String transactionId = receiptUtil.extractTransactionIdFromAppReceipt(appReceipt);

**Comment by linkaiqq** [comment]
The appReceipt verification has been consistently abnormal, using JDK17

**Comment by alexanderjordanbaker** [comment]
Please make sure you do not have a conflicting version of bouncy castle on your class path
