### ISSUE TITLE
API exception 500 Unavailable at Nov 12, 2024 14:10:09.000 - 14:20:09.000 (time zone GMT+8)

### ISSUE THREAD

**Issue by hakusai22** [apple/app-store-server-library-java#130]
<img width="2077" alt="image" src="https://github.com/user-attachments/assets/d06fa872-205a-4215-afe9-fb27852d4881">

- Hello, do you have time to look at this for me?
```
APIException{httpStatusCode=500, apiError=null, apiErrorMessage='null'}
```

**Comment by alexanderjordanbaker** [comment]
@hakusai22 What is the question here?
