### ISSUE TITLE
ReceiptUtility.extractTransactionIdFromAppReceipt signature question

### ISSUE THREAD

**Issue by pomadchin** [apple/app-store-server-library-java#20]
What's the criteria right now the `transactionId` is extracted from the `appReceipt`? Should not it return a `Set` of `(original)transactionIds` / a lit of all `transactionIds`?

Sometimes `appReceipts` may contain a lot of transactions that may have different `originalTransactionId`s (i.e. a regular subscription + ppvs (some of them may be active)).

**Comment by alexanderjordanbaker** [comment]
For the App Store Server API endpoints, like the Get Transaction History endpoint, which transaction id is used does not matter, since all transactions are returned.
