### ISSUE TITLE
Decoded notification data does not contain status

### ISSUE THREAD

**Issue by vpavic** [apple/app-store-server-library-java#32]
Firstly, thanks for providing this library. Though still in beta phase, it has been very helpful to us while integrating with the App Store.

App Store [server notifications documentation](https://developer.apple.com/documentation/appstoreservernotifications/data) states that decoded payload notification data contains status of an auto-renewable subscription. However the class that maps this information, [`com.apple.itunes.storekit.model.Data`](https://github.com/apple/app-store-server-library-java/blob/main/src/main/java/com/apple/itunes/storekit/model/Data.java), does not support this. I assume this is because the addition of status is quite recent, judging by server notifications [changelog entry from June](https://developer.apple.com/documentation/appstoreservernotifications/app_store_server_notifications_changelog#4208448).

As subscription state is quite fundamental to managing subscriptions on the backend, could you please add support for this, a hopefully publish a `0.1.3` soon? I'm also willing to provide a PR if that would help speed up things a bit.

**Comment by alexanderjordanbaker** [comment]
@vpavic Thank you for this report, this has been resolved in
https://github.com/apple/app-store-server-library-python/pull/33
https://github.com/apple/app-store-server-library-node/pull/21
https://github.com/apple/app-store-server-library-swift/pull/7
https://github.com/apple/app-store-server-library-java/pull/34

**Comment by vpavic** [comment]
Thanks for addressing this. When could we expect `0.1.3` to be published?

Though I must note - quite a poor contributor experience here, after submitting PR #33 to address this only to see it ignored and superseded by almost the same PR in #34.

**Comment by alexanderjordanbaker** [comment]
@vpavic Apologies for the superseding. When creating the PR I created for all four repositories at once, and didn't account for your PR. I will pay closer attention in the future, and thank you for working to improve the project
