### ISSUE TITLE
Consider renaming `Status` enums to avoid clashes

### ISSUE THREAD

**Issue by vpavic** [apple/app-store-server-library-java#35]
The project contains 2 enums named `Status`:

- `com.apple.itunes.storekit.model.Status`
- `com.apple.itunes.storekit.verification.Status`

This is unfortunate because if one needs to use both in the same class, one has to be referred to with fully-qualified class name.

Perhaps these enums could be renamed to be more specific (for example, `SubscriptionStatus` and `VerificationStatus`)?

**Comment by alexanderjordanbaker** [comment]
Resolved in #59
