### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by vpavic** [apple/app-store-server-library-java#42]
As evident by some recent issues like #32 and #37, test coverage in this project is quite low.

For example, `SignedDataVerifier` only verifies test notification type and not others that are truly relevant and `ReceiptUtility` is completely untested.

**Comment by alexanderjordanbaker** [comment]
Hello @vpavic we have now increased our test coverage and aim to test all major flows in some recent PRs to add additional coverage.

**Comment by alexanderjordanbaker** [comment]
This was resolved in #51

**Comment by vpavic** [comment]
Thanks for the update @alexanderjordanbaker, I just went through all the changes that were merged over the past few weeks and the situation is now indeed better.

I'd just suggest to add some more test cases for server notifications, because the only tested notification is one of type `TEST` and those don't really have much data on them and therefore do not adequately test the whole decoding and verification functionality.

**Comment by alexanderjordanbaker** [comment]
@vpavic I think this is the test you are looking for, it does a more comprehensive test of the actual decoding of notifications https://github.com/apple/app-store-server-library-java/blob/main/src/test/java/com/apple/itunes/storekit/model/ResponseBodyV2DecodedPayloadTest.java

The tests treat the verification pieces (x5c header that kind of thing) separately from the making sure the model decoding is correct

**Comment by vpavic** [comment]
Thanks, I missed that one, it indeed is what I was looking for.
