### ISSUE TITLE
Is it possible to lower the minimum JDK version to 1.8? This would save users a lot of upgrade work.

### ISSUE THREAD

**Issue by Karl-Sparticle** [apple/app-store-server-library-java#44]
And I have done a part of the work.
https://github.com/Karl-Sparticle/app-store-server-library-java

**Comment by alexanderjordanbaker** [comment]
@Karl-Sparticle Thank you for opening the issue. At this time we are not looking to support Java 8 and have a target compatibility of 11 for our release JARs
