### ISSUE TITLE
【Enhance】Not found is_trial_period from JWSTransactionDecodedPayload

### ISSUE THREAD

**Issue by itweixiang** [apple/app-store-server-library-java#45]
### Purpose

I want to distinguish between trial subscriptions and regular subscriptions

### First

the url , `https://sandbox.itunes.apple.com/verifyReceipt` , is deprecated. 

Generally, the is_trial_period field corresponding to transaction_id is obtained according to the return result of the interface to distinguish whether to trial 

but the url is deprecated , I also want to use the latest api

### But

I use this SDK , such as: 
```java
            TransactionInfoResponse transactionInfo = appleClient.getTransactionInfo(transactionId);
            JWSTransactionDecodedPayload payload = appleVerifier.verifyAndDecodeTransaction(transactionInfo.getSignedTransactionInfo());
```

payload  is :
```
{
    "originalTransactionId": "xxx",
    "transactionId": "xxx",
    "webOrderLineItemId": "xxx",
    "bundleId": "com.xxx.xxx",
    "productId": "com.xxx.xxx.xxx.0004",
    "subscriptionGroupIdentifier": "xxx",
    "purchaseDate": 1697509633000,
    "originalPurchaseDate": 1695127047000,
    "expiresDate": 1697509813000,
    "quantity": 1,
    "type": "Auto-Renewable Subscription",
    "inAppOwnershipType": "PURCHASED",
    "signedDate": 1697526007839,
    "offerType": "1",
    "environment": "Sandbox",
    "storefront": "CHN",
    "storefrontId": "xxx",
    "transactionReason": "PURCHASE"
}
```

I not found field of is_trial_period  or able to identify trial fields

**Comment by itweixiang** [comment]
How do I know if I want to try it out when using this SDK

**Comment by alexanderjordanbaker** [comment]
https://developer.apple.com/documentation/appstoreserverapi/jwstransactiondecodedpayload Does not provide an is_trial_period field. The closest would be https://developer.apple.com/documentation/appstoreserverapi/offertype

Feedback for the underlying endpoints in the App Store Server API should be submitted via https://feedbackassistant.apple.com/

**Comment by itweixiang** [comment]
thank for your reply
