### ISSUE TITLE
Serialization errors with transaction model

### ISSUE THREAD

**Issue by Ashakibp** [apple/app-store-server-library-java#46]
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.apple.itunes.storekit.model.Type` from String "Auto-Renewable Subscription": not one of the values accepted for Enum class: [CONSUMABLE, AUTO_RENEWABLE_SUBSCRIPTION, NON_CONSUMABLE, NON_RENEWING_SUBSCRIPTION]

**Comment by alexanderjordanbaker** [comment]
Hello, our library does not use Jackson, it uses GSON, and it looks like you don’t have Jackson wired to use the value of the String variable in the enum instead of the enum name
