### ISSUE TITLE
[UPDATE] Attribute Price NOT appears on JWSTransactionDecodedPayload

### ISSUE THREAD

**Issue by ArnauKokoro** [apple/app-store-server-library-java#56]
Hi,

Could you please release new version to JWSTransactionDecodedPayload have price.

Thanks!

**Comment by ruofeilyu** [comment]
Very needed!

**Comment by ruofeilyu** [comment]
Very needed!!

**Comment by alexanderjordanbaker** [comment]
This was resolved in #53

**Comment by hankovich** [comment]
@alexanderjordanbaker do you know why Store Server API stopped returning price and currency in their responses?
Several days ago all decoded transactions contained both `price` and `currency` fileds, but today I see that *all* responses come without these fields

**Comment by hankovich** [comment]
It looks like it was a bug, the issue is resolved now, Apple returns price and currency as expected
