### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by Cubeatz** [apple/app-store-server-library-java#70]
I have to setup a proxy to send,but it dosen't working

I had to modify the code of _com.apple.itunes.storekit.client.AppStoreServerAPIClient_.Code like this:

```
Proxy proxyTest = new Proxy(Proxy.Type.HTTP,new InetSocketAddress("proxy", proxyPort));
OkHttpClient client = new OkHttpClient.Builder().proxy(proxyTest).build();
AppStoreServerAPIClient client =
                new AppStoreServerAPIClient(encodedKey, keyId, issuerId, bundleId, environment,client);
```

```
public AppStoreServerAPIClient(String signingKey, String keyId, String issuerId, String bundleId, Environment environment,OkHttpClient httpClient) {
        this.bearerTokenAuthenticator = new BearerTokenAuthenticator(signingKey, keyId, issuerId, bundleId);
        this.httpClient = httpClient;
        this.urlBase = HttpUrl.parse(environment.equals(Environment.SANDBOX) ? SANDBOX_URL : PRODUCTION_URL);
        this.objectMapper = new ObjectMapper();
        objectMapper.setVisibility(objectMapper.getSerializationConfig().getDefaultVisibilityChecker()
                .withFieldVisibility(JsonAutoDetect.Visibility.ANY)
                .withGetterVisibility(JsonAutoDetect.Visibility.NONE)
                .withIsGetterVisibility(JsonAutoDetect.Visibility.NONE)
                .withSetterVisibility(JsonAutoDetect.Visibility.NONE)
                .withCreatorVisibility(JsonAutoDetect.Visibility.NONE));
    }
```

PLEASE REPAIR IT.

**Comment by alexanderjordanbaker** [comment]
@Cubeatz Do the Java built-in proxy config options not work? Example:
`-Dhttp.proxyHost=1.2.3.4 -Dhttp.proxyPort=1234`

**Comment by Cubeatz** [comment]
> @Cubeatz Do the Java built-in proxy config options not work? Example: `-Dhttp.proxyHost=1.2.3.4 -Dhttp.proxyPort=1234`

I think is not a good idea.If I configure these configurations, it will make all http requests go through the proxy.

In this example,I just want IAP to be accessed through a proxy

**Comment by Cubeatz** [comment]
> If you need more fine-grained control, Java provides java.net.ProxySelector::setDefault, which OKHttp uses, which can be used to only enable proxies on a per-endpoint basis

But the constructor of class _AppStoreServerAPIClient_ has only one method without param OKhttp, which is confusing.
![image](https://github.com/apple/app-store-server-library-java/assets/44158309/ab482f22-4842-404a-97d1-c2d572e8ff43)

And in the api example,I don't see the entrance to the finer-grained control.If you have idea,please give us an example.
<img width="921" alt="image" src="https://github.com/apple/app-store-server-library-java/assets/44158309/f5247e84-1f7a-4b83-be14-de8d3878bf28">

Thanks!


> 如果您需要更细粒度的控制，Java 提供了 OKHttp 使用的 java.net.ProxySelector::setDefault，它可用于仅在每个端点上启用代理

**Comment by alexanderjordanbaker** [comment]
This is a rough outline, but something like this. Java has a lot of customization options built into its proxy configs

```java
        java.net.ProxySelector.setDefault(new ProxySelector() {
            public List<Proxy> select(URI uri) {
                if ("api.storekit.itunes.apple.com".equals(uri.getHost()) || "api.storekit-sandbox.itunes.apple.com".equals(uri.getHost())) {
                    Proxy proxyTest = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("proxy", proxyPort));
                    return List.of(proxyTest);
                }
                return List.of(Proxy.NO_PROXY);
            }

            public void connectFailed(URI uri, SocketAddress sa, IOException ioe) {}
        });
```

**Comment by Cubeatz** [comment]
All right.Please add to the readme.Thanks!
