### ISSUE TITLE
What should I do if I don’t know which app the callback information belongs to?

### ISSUE THREAD

**Issue by hakusai22** [apple/app-store-server-library-java#73]
I have more than a dozen apps setting the same callback address in the background. My new AppStoreServerAPIClient(encodedKey, keyId, issuerId, bundleId, environment); I don’t know which app the callback information belongs to, so I don’t know who to change. Configuration information, is there a solution to this? For example, I don't verify the first layer of base64 and directly decrypt it. After getting the bundleId, can I determine which app it is?

<img width="913" alt="image" src="https://github.com/apple/app-store-server-library-java/assets/58761705/26c60cd8-c859-4d92-8e82-3fc0ab02fefc">

**Comment by alexanderjordanbaker** [comment]
In this case, we recommend in App Store Connect adding a query param or some other identifier to the URL to allow your server to know which app the notification URL is being called for, but still allowing them to all share the same domain and path.

**Comment by hakusai22** [comment]
Thanks for the reply. The method used is to add a unique identifier after each callback address. Another point is to distinguish between the sandbox and the production environment. It is also necessary to add an identifier after the link.
