### ISSUE TITLE
Add method parameters in AppStoreServerAPIClient methods to accept bearer token

### ISSUE THREAD

**Issue by sagar-rai** [apple/app-store-server-library-java#88]
As a developer i think that while following a good design pattern, most of the services should create a single instance of the client for the production environment, providing a method to pass a bearer token, takes away the need to maintaining and refreshing the client every 5 minutes(expiry of the jwt bearer token). This still maintains security since the dev does not hardcode any secrets in config/code and still provides the flexibility to not create a client on the fly or maintain the overhead of refresh.

@alexanderjordanbaker what do you think, is it fine to open a pr for the same.

**Comment by sagar-rai** [comment]
nvm, i checked the code, token is generated for each request

**Comment by alexanderjordanbaker** [comment]
Yep! This client should ideally be a singleton, it will handle token re-creation
