### ISSUE TITLE
hello, I would like to ask under what circumstances will apple callback to be empty?

### ISSUE THREAD

**Issue by hakusai22** [apple/app-store-server-library-java#90]
hello, I would like to ask under what circumstances will apple callback to be empty?
https://developer.apple.com/documentation/appstoreservernotifications/signedpayload?changes=_3

<img width="853" alt="image" src="https://github.com/apple/app-store-server-library-java/assets/58761705/80888b7f-5e01-49b2-88fc-1d49a13402b9">

<img width="702" alt="image" src="https://github.com/apple/app-store-server-library-java/assets/58761705/ddc0aa86-aa36-44c4-a1ec-0aef62393412">

**Comment by alexanderjordanbaker** [comment]
Is this related to the library? I don’t see any library classes in this screenshot

**Comment by alexanderjordanbaker** [comment]
@hakusai22 It generally isn’t possible to have a null callback, from Apple

**Comment by hakusai22** [comment]
> @hakusai22 It generally isn’t possible to have a null callback, from Apple

In my production environment, there are many null callbacks.
