### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by damonho** [apple/app-store-server-library-java#91]
Hi, I have to configure this library to use a proxy that requires authentication.

I see theres a previous issue opened about this #70, however the solution presented there don't quite work with auth.
From https://github.com/square/okhttp/issues/4108, the okhttp library used doesn't respect `java.net.Authenticator.setDefault`, only `java.net.ProxySelector.setDefault`. 

We have to set the authenticator in the client builder for it to be used.
https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#proxyAuthenticator-okhttp3.Authenticator-

Are we able to add a constructor for the `AppStoreServerAPIClient` that lets us pass in the `OkHttpClient`?

**Comment by alexanderjordanbaker** [comment]
@damonho Would configuring the OKHttpClient client's proxyAuthenticator to be Authenticator.JAVA_NET_AUTHENTICATOR be sufficient for your use case?

**Comment by damonho** [comment]
@alexanderjordanbaker That sounds like it should work as well for my use case 👍
