### ISSUE TITLE
an exception appears with httpStatusCode=401, apiError=null, apiErrorMessage='null'

### ISSUE THREAD

**Issue by hakusai22** [apple/app-store-server-library-java#96]
When calling the getAllSubscriptionStatuses(String transactionId, Status[] status) method in a production environment, an exception occasionally occurs, httpStatusCode=401, apiError=null, apiErrorMessage='null'. All my configurations are unified. When I create the AppStoreServerAPIClient, this exception will occasionally occur. I don't understand the triggering scenario of this accidental exception.

https://developer.apple.com/documentation/appstoreserverapi/get_all_subscription_statuses
<img width="1232" alt="image" src="https://github.com/apple/app-store-server-library-java/assets/58761705/8d64c7f3-a76a-4c9f-afe0-de3da252b34d">

<img width="1555" alt="image" src="https://github.com/apple/app-store-server-library-java/assets/58761705/28ba7653-8891-453f-aead-c12e1d0d5307">

```log
2024-05-04,02:05:40,233 ERROR a73a88cd [TID: N/A] cn.lollypop.www.xxxx.utils.RpcExceptionHandler: fail
cn.lollypop.common.base.exception.LollypopServerException: APIException{httpStatusCode=401, apiError=null, apiErrorMessage='null'}
```

**Comment by hakusai22** [comment]
`
    public String generateToken() {
        return JWT.create()
                .withAudience(APP_STORE_CONNECT_AUDIENCE)
                .withExpiresAt(Instant.now().plus(ChronoUnit.MINUTES.getDuration().multipliedBy(5)))
                .withIssuer(issuerId)
                .withKeyId(keyId)
                .withPayload(Map.of(BUNDLE_ID_KEY, bundleId))
                .sign(Algorithm.ECDSA256(signingKey));
    }
`

I see that the code for generating tokens is one-time and newly generated. Why does 401 appear?

**Comment by hakusai22** [comment]
@alexanderjordanbaker hello ,If you have time, can you help me analyze this problem? Thank you. There have been a lot of 401s in the production environment recently.

**Comment by pkgonan** [comment]
Oh my god. 

I've been experiencing this problem recently as well. I was searching google over and over again and found the same problem here now.

I keep getting the 401 error from time to time. This seems like a bug from Apple.

**Comment by hakusai22** [comment]
> Oh my god.
> 
> I've been experiencing this problem recently as well. And it's still happening today.
> 
> I was searching google over and over again and found the same problem here now.
> 
> I keep getting the 401 error from time to time. This seems like a bug from Apple.

Most requests are successful, but some requests result in 401?

**Comment by alexanderjordanbaker** [comment]
@hakusai22 Let me take a look and get back to you

**Comment by drewster99** [comment]
any update on this?

**Comment by pkgonan** [comment]
> > Oh my god.
> > I've been experiencing this problem recently as well. And it's still happening today.
> > I was searching google over and over again and found the same problem here now.
> > I keep getting the 401 error from time to time. This seems like a bug from Apple.
> 
> Most requests are successful, but some requests result in 401?

Exactly, yes.

And, as a separate issue, API calls to Apple apps that are not yet set up in production also result in a 401 error. The 401 error shouldn't occur because the JWT is correct.

The official guidance from Apple says to try calling the Production API first and if the response is invalid, try calling the Sandbox API, but a 401 response doesn't seem appropriate.

**Comment by alexanderjordanbaker** [comment]
@hakusai22 This should be improved now, please let me know if you continue to experience this issue

**Comment by hakusai22** [comment]
> @hakusai22 This should be improved now, please let me know if you continue to experience this issue

<img width="1651" alt="image" src="https://github.com/apple/app-store-server-library-java/assets/58761705/bf0efdac-74da-49ad-b0a8-a53821c50195">
This abnormal situation still appeared in the log today. My version is still 2.0.0

**Comment by alexanderjordanbaker** [comment]
@hakusai22 This is after my post?

**Comment by alexanderjordanbaker** [comment]
Wait that status code is 500?

**Comment by hakusai22** [comment]
> Wait that status code is 500?

For my business, this is a 500 exception. The official API returns 401.

**Comment by hakusai22** [comment]
> @hakusai22 This is after my post?

About an hour before you posted

**Comment by alexanderjordanbaker** [comment]
@hakusai22 I checked the logs, you were 6 minutes before the change deployed. Please let me know if you see it again now that the change is out

**Comment by hakusai22** [comment]
@alexanderjordanbaker OK, I'll take a look. What's the reason?

**Comment by shubham-scaletech** [comment]
I would advise everyone to go through this official video provided by apple, to handle server api. i was able to send test notification by following this video.
[app store server library](https://developer.apple.com/videos/play/wwdc2023/10143/)
