### ISSUE TITLE
ConsumptionRequest model does not match the documentation

### ISSUE THREAD

**Issue by nicoleSv** [apple/app-store-server-library-java#99]
The documentation for the Send Consumption Information endpoint says the following:

> 
The [ConsumptionRequest](https://developer.apple.com/documentation/appstoreserverapi/consumptionrequest) response body requires that you set the appAccountToken value to a valid value of either a UUID or an empty string.

However, in the implementation of this library the [appAccountToken](https://developer.apple.com/documentation/appstoreserverapi/appaccounttoken) is defined as an UUID object which cannot be serialized to an emptry string as it is not a valid UUID. This makes it impossible to use the model and send a ConsumptionRequest if we do not have an appAccountToken which is a valid case.

**Comment by alexanderjordanbaker** [comment]
Hello @nicoleSv, thank you for reaching out. You are right, a null UUID should be serialized as an empty string, I will work on correcting that
